services:
  - type: web
    name: Estoque_DJANGO
    env: python
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: SECRET_KEY
        value: your-secret-key