# Generated by Django 5.1.2 on 2024-12-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacoes',
            name='data_chegada_saida',
            field=models.DateField(),
        ),
    ]
