# Generated by Django 5.1.1 on 2024-12-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0002_alter_movimentacoes_data_chegada_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacoes',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=10),
        ),
    ]
