# Generated by Django 5.1.1 on 2024-12-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='formato',
            field=models.CharField(choices=[('null', 'null'), ('640x880', '640x880'), ('660x960', '660x960')], max_length=255),
        ),
    ]
