# Generated by Django 5.1.2 on 2024-12-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoqueMin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
